### PR TITLE
Add invoke-generate-images script

### PR DESCRIPTION
**Pull request by RyanJDick**
Adds a script for generating a dataset of images from a single prompt. This will be used by DreamBooth training.

### CODE REVIEW

**Comment by brandonrising** [comment]
is there a reason to use this over the invokeai cli?

**Comment by brandonrising** [comment]
The lack of single letter flags in the CLI could be a painpoint if people regularly use this

**Comment by RyanJDick** [comment]
> is there a reason to use this over the invokeai cli?

Honestly, that didn't even cross my mind until you mentioned it. Maybe I'm missing something, but from poking around the invokeai CLI docs it seemed like it would be complicated to achieve this same result. I think it's nice to have a simple, single-purpose, standalone script for this use case.

**Comment by RyanJDick** [comment]
> The lack of single letter flags in the CLI could be a painpoint if people regularly use this

Added short options for all params that could be easily shortened without name conflicts: [95fbcbc](https://github.com/invoke-ai/invoke-training/pull/28/commits/95fbcbc4d41d04db6d785dc0402914107d0d0214)

**Review by brandonrising — APPROVED** [review]

**Pull request merged**
