### PR TITLE
Add a Gradio app for dataset annotation

### PR DESCRIPTION
**Pull request by RyanJDick**
This PR adds a gradio page to `invoke-train-ui` for creating datasets and captioning images.

### CODE REVIEW

**Comment by hipsterusername** [comment]
Before we add anything else, think performance on this needs to be checked. Currently loading images at ~10s/image from an SSD

**Comment by hipsterusername** [comment]
Unclear where this issue is coming from but

> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "C:\Users\kentr\invoke-training\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
>     data = fetcher.fetch(index)
>   File "C:\Users\kentr\invoke-training\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "C:\Users\kentr\invoke-training\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "C:\Users\kentr\invoke-training\invoke-training\src\invoke_training\_shared\data\datasets\transform_dataset.py", line 23, in __getitem__
>     example = self._base_dataset[idx]
>   File "C:\Users\kentr\invoke-training\invoke-training\src\invoke_training\_shared\data\datasets\image_caption_jsonl_dataset.py", line 79, in __getitem__
>     image = self._load_image(self._get_image_path(idx))
>   File "C:\Users\kentr\invoke-training\invoke-training\src\invoke_training\_shared\data\datasets\image_caption_jsonl_dataset.py", line 53, in _get_image_path
>     image_path = self._jsonl_path.parent / image_path
> AttributeError: 'str' object has no attribute 'parent'

This is an error from **training** when using a .jsonl dataset generated using the data annotation tab.

All lines of .jsonl are formatted as below --
{"image": "C:\\Users\\kentr\\invoke-training\\datasets\\prophoto\\1293.jpg", "text": "a man with sunglasses, sunset, backlit"}

**Comment by RyanJDick** [comment]
> Before we add anything else, think performance on this needs to be checked. Currently loading images at ~10s/image from an SSD

Discussed in-person. This is an issue with large image files. Possibly related to https://github.com/gradio-app/gradio/issues/2635. We are going to punt on addressing this for now.

**Comment by RyanJDick** [comment]
> df50169

Fixed in [df50169](https://github.com/invoke-ai/invoke-training/pull/93/commits/df5016971011bf107f6ecb90f7242bd7e044749d). Looks like it was caught by the unit tests in the failing build 🎉

**Comment by RyanJDick** [comment]
> Unclear where this issue is coming from but
> 
> > AttributeError: Caught AttributeError in DataLoader worker process 0.
> > Original Traceback (most recent call last):
> > File "C:\Users\kentr\invoke-training\venv\lib\site-packages\torch\utils\data_utils\worker.py", line 308, in _worker_loop
> > data = fetcher.fetch(index)
> > File "C:\Users\kentr\invoke-training\venv\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "C:\Users\kentr\invoke-training\venv\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in 
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "C:\Users\kentr\invoke-training\invoke-training\src\invoke_training_shared\data\datasets\transform_dataset.py", line 23, in **getitem**
> > example = self._base_dataset[idx]
> > File "C:\Users\kentr\invoke-training\invoke-training\src\invoke_training_shared\data\datasets\image_caption_jsonl_dataset.py", line 79, in **getitem**
> > image = self._load_image(self._get_image_path(idx))
> > File "C:\Users\kentr\invoke-training\invoke-training\src\invoke_training_shared\data\datasets\image_caption_jsonl_dataset.py", line 53, in _get_image_path
> > image_path = self._jsonl_path.parent / image_path
> > AttributeError: 'str' object has no attribute 'parent'
> 
> This is an error from **training** when using a .jsonl dataset generated using the data annotation tab.
> 
> All lines of .jsonl are formatted as below -- {"image": "C:\Users\kentr\invoke-training\datasets\prophoto\1293.jpg", "text": "a man with sunglasses, sunset, backlit"}

Fixed in [df50169](https://github.com/invoke-ai/invoke-training/pull/93/commits/df5016971011bf107f6ecb90f7242bd7e044749d). Looks like it was caught by the unit tests in the failing build 🎉

**Pull request merged**
